<?php

namespace App\DTO\ImportPayIn;

final class ShippingPayInCsvDataDTO
{
    public function __construct(
        public readonly string $symbol_spedytora,
        public readonly string $numer_listu,
        public readonly string $nr_faktury_do_ktorej_dany_lp_zostal_przydzielony,
        public readonly string $data_nadania_otrzymania,
        public readonly string $nr_i_d,
        public string          $rzeczywisty_koszt_transportu_brutto,
        public readonly string $wartosc_pobrania,
        public readonly string $file,
        public readonly string $reszta,
        public readonly string $rodzaj,
        public readonly string $pfc,
        public readonly string $parcel_num,
        public readonly string $parcel_status,
        public readonly string $rname1,
        public readonly string $rname2,
        public readonly string $rname3,
        public readonly string $rcountry,
        public readonly string $rpost,
        public readonly string $rcity,
        public readonly string $rstreet,
        public readonly string $content,
        public readonly string $note1,
        public readonly string $weight,
        public readonly string $date,
        public readonly string $kwota_pobrania,
        public readonly string $zamówienie,
        public readonly string $numer_przesylki,
        public readonly string $nr_referencyjny_klienta,
        public readonly string $www,
        public readonly string $id,
        public readonly string $walidacja,
        public readonly string $zatwierdzona,
        public readonly string $pobranie,
        public readonly string $zwrot_palet,
        public readonly string $zwrot_dokumentów,
        public readonly string $status,
        public readonly string $iloœc_palet,
        public readonly string $cena_szacunkowa,
        public readonly string $platnik,
        public readonly string $data_zlecenia,
        public readonly string $data_podjecia_od,
        public readonly string $data_podjecia_do,
        public readonly string $czas_podjecia_od,
        public readonly string $czas_podjecia_do,
        public readonly string $data_doreczenia_od,
        public readonly string $data_doreczenia_do,
        public readonly string $czas_doreczenia_od,
        public readonly string $czas_doreczenia_do,
        public readonly string $nadawca_symbol,
        public readonly string $nadawca,
        public readonly string $nadawca_kraj,
        public readonly string $nadawca_miasto,
        public readonly string $nadawca_kod_poczt,
        public readonly string $odbiorca_symbol,
        public readonly string $odbiorca,
        public readonly string $odbiorca_kraj,
        public readonly string $odbiorca_miasto,
        public readonly string $odbiorca_kod_poczt,
        public readonly string $miejsce_podjecia_nazwa,
        public readonly string $miejsce_podjecia_adres,
        public readonly string $miejsce_podjecia_kod,
        public readonly string $miejsce_podjecia_miasto,
        public readonly string $miejsce_podjecia_kraj,
        public readonly string $miejsce_dostawy_nazwa,
        public readonly string $miejsce_dostawy_adres,
        public readonly string $miejsce_dostawy_kod,
        public readonly string $miejsce_dostawy_miasto,
        public readonly string $miejsce_dostawy_kraj,
        public readonly string $iloœc_deklarowana,
        public readonly string $waga_deklarowana,
        public readonly string $objetoœc_deklarowana,
        public readonly string $waga_przesylki,
        public readonly string $objetoœc_przesylki,
        public readonly string $punkty_a_d_r,
        public readonly string $ilosc_l_q_a_d_r,
        public readonly string $ilosc_e_q_a_d_r,
        public readonly string $a_d_r,
        public readonly string $s_e_n_t,
        public readonly string $data_doreczenia_rzeczywista,
    ) {}

    /**
     * Convert DTO to array
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'symbol_spedytora' => $this->symbol_spedytora,
            'numer_listu' => $this->numer_listu,
            'nr_faktury_do_ktorej_dany_lp_zostal_przydzielony' => $this->nr_faktury_do_ktorej_dany_lp_zostal_przydzielony,
            'data_nadania_otrzymania' => $this->data_nadania_otrzymania,
            'nr_i_d' => $this->nr_i_d,
            'rzeczywisty_koszt_transportu_brutto' => $this->rzeczywisty_koszt_transportu_brutto,
            'wartosc_pobrania' => $this->wartosc_pobrania,
            'file' => $this->file,
            'reszta' => $this->reszta,
            'rodzaj' => $this->rodzaj,
            'pfc' => $this->pfc,
            'parcel_num' => $this->parcel_num,
            'parcel_status' => $this->parcel_status,
            'rname1' => $this->rname1,
            'rname2' => $this->rname2,
            'rname3' => $this->rname3,
            'rcountry' => $this->rcountry,
            'rpost' => $this->rpost,
            'rcity' => $this->rcity,
            'rstreet' => $this->rstreet,
            'content' => $this->content,
            'note1' => $this->note1,
            'weight' => $this->weight,
            'date' => $this->date,
            'kwota_pobrania' => $this->kwota_pobrania,
            'zamówienie' => $this->zamówienie,
            'numer_przesylki' => $this->numer_przesylki,
            'nr_referencyjny_klienta' => $this->nr_referencyjny_klienta,
            'www' => $this->www,
            'id' => $this->id,
            'walidacja' => $this->walidacja,
            'zatwierdzona' => $this->zatwierdzona,
            'pobranie' => $this->pobranie,
            'zwrot_palet' => $this->zwrot_palet,
            'zwrot_dokumentów' => $this->zwrot_dokumentów,
            'status' => $this->status,
            'iloœc_palet' => $this->iloœc_palet,
            'cena_szacunkowa' => $this->cena_szacunkowa,
            'platnik' => $this->platnik,
            'data_zlecenia' => $this->data_zlecenia,
            'data_podjecia_od' => $this->data_podjecia_od,
            'data_podjecia_do' => $this->data_podjecia_do,
            'czas_podjecia_od' => $this->czas_podjecia_od,
            'czas_podjecia_do' => $this->czas_podjecia_do,
            'data_doreczenia_od' => $this->data_doreczenia_od,
            'data_doreczenia_do' => $this->data_doreczenia_do,
            'czas_doreczenia_od' => $this->czas_doreczenia_od,
            'czas_doreczenia_do' => $this->czas_doreczenia_do,
            'nadawca_symbol' => $this->nadawca_symbol,
            'nadawca' => $this->nadawca,
            'nadawca_kraj' => $this->nadawca_kraj,
            'nadawca_miasto' => $this->nadawca_miasto,
            'nadawca_kod_poczt' => $this->nadawca_kod_poczt,
            'odbiorca_symbol' => $this->odbiorca_symbol,
            'odbiorca' => $this->odbiorca,
            'odbiorca_kraj' => $this->odbiorca_kraj,
            'odbiorca_miasto' => $this->odbiorca_miasto,
            'odbiorca_kod_poczt' => $this->odbiorca_kod_poczt,
            'miejsce_podjecia_nazwa' => $this->miejsce_podjecia_nazwa,
            'miejsce_podjecia_adres' => $this->miejsce_podjecia_adres,
            'miejsce_podjecia_kod' => $this->miejsce_podjecia_kod,
            'miejsce_podjecia_miasto' => $this->miejsce_podjecia_miasto,
            'miejsce_podjecia_kraj' => $this->miejsce_podjecia_kraj,
            'miejsce_dostawy_nazwa' => $this->miejsce_dostawy_nazwa,
            'miejsce_dostawy_adres' => $this->miejsce_dostawy_adres,
            'miejsce_dostawy_kod' => $this->miejsce_dostawy_kod,
            'miejsce_dostawy_miasto' => $this->miejsce_dostawy_miasto,
            'miejsce_dostawy_kraj' => $this->miejsce_dostawy_kraj,
            'ilosc_l_q_a_d_r' => $this->ilosc_l_q_a_d_r,
        ];
    }
}
