export const SETS_SET_ALL = 'SETS_SET_ALL'
export const SETS_SET_ERROR = 'SETS_SET_ERROR'
export const SETS_SET_IS_LOADING = 'SETS_SET_IS_LOADING'
export const SETS_SET_PRODUCTS = 'SETS_SET_PRODUCTS'
