<?php

return [
    'customers' => [
        'first_group' => [
            'super_admin' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                    'nick_allegro' => 3,
                    'status' => 14
                ],
                'hide' => [
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                ]
            ],
            'admin' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                    'nick_allegro' => 3,
                    'status' => 14
                ],
                'hide' => [
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                ]
            ],
            'accountant' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                    'nick_allegro' => 3,
                    'status' => 14
                ],
                'hide' => [
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                ]
            ],
            'consultant' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                    'nick_allegro' => 3,
                    'status' => 14
                ],
                'hide' => [
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                ]
            ],
            'storekeeper' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                    'nick_allegro' => 3,
                    'status' => 14
                ],
                'hide' => [
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                ]
            ]
        ],
        'second_group' => [
            'super_admin' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                ],
                'hide' => [
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                    'status' => 14
                ]
            ],
            'admin' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                ],
                'hide' => [
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                    'status' => 14
                ]
            ],
            'accountant' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                ],
                'hide' => [
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                    'status' => 14
                ]
            ],
            'consultant' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                ],
                'hide' => [
                    'nick_allegro' => 3,
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                    'status' => 14
                ]
            ],
            'storekeeper' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                ],
                'hide' => [
                    'nick_allegro' => 3,
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                    'status' => 14
                ]
            ]
        ],
        'show_all' => [
            'super_admin' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                    'nick_allegro' => 3,
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                    'status' => 14
                ],
                'hide' => [
                ]
            ],
            'admin' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                    'nick_allegro' => 3,
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                    'status' => 14
                ],
                'hide' => [
                ]
            ],
            'accountant' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                    'nick_allegro' => 3,
                    'status' => 14,
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                ],
                'hide' => [

                ]
            ],
            'consultant' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                    'nick_allegro' => 3,
                    'status' => 14
                ],
                'hide' => [
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                ]
            ],
            'storekeeper' => [
                'show' => [
                    'id' => 1,
                    'login' => 2,
                    'nick_allegro' => 3,
                    'status' => 14
                ],
                'hide' => [
                    'standard_firstname' => 4,
                    'standard_lastname' => 5,
                    'standard_firmname' => 6,
                    'standard_nip' => 7,
                    'standard_phone' => 8,
                    'standard_address' => 9,
                    'standard_flat_number' => 10,
                    'standard_city' => 11,
                    'standard_postal_code' => 12,
                    'standard_email' => 13,
                ]
            ]
        ],
    ],
    'orders' => [
        'first_group' => [
            'super_admin' => [
                'show' => [
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.address.firstname' => 14,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                    
                ],
                'hide' => [
                    'id' => 1,
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'customer.addresses.email' => 13,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ]
            ],
            'admin' => [
                'show' => [
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.address.firstname' => 14,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                ],
                'hide' => [
                    'id' => 1,
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'customer.addresses.email' => 13,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ]
            ],
            'accountant' => [
                'show' => [
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.address.firstname' => 14,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                ],
                'hide' => [
                    'id' => 1,
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'customer.addresses.email' => 13,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ]
            ],
            'consultant' => [
                'show' => [
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.address.firstname' => 14,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                ],
                'hide' => [
                    'id' => 1,
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'customer.addresses.email' => 13,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ]
            ],
            'storekeeper' => [
                'show' => [
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.address.firstname' => 14,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                ],
                'hide' => [
                    'id' => 1,
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'customer.addresses.email' => 13,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ]
            ]
        ],
        'second_group' => [
            'super_admin' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'actions' => 7,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'shipment_price_for_client' => 22,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    
                ],
                'hide' => [
                    'id' => 1,
                    'created_at' => 6,
                    'section' => 8,
                    'customer.addresses.email' => 13,
                    'customer.address.firstname' => 14,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'profit' => 17,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,

                ]
            ],
            'admin' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'actions' => 7,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'shipment_price_for_client' => 22,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                ],
                'hide' => [
                    'id' => 1,
                    'created_at' => 6,
                    'section' => 8,
                    'customer.addresses.email' => 13,
                    'customer.address.firstname' => 14,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'profit' => 17,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ]
            ],
            'accountant' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'actions' => 7,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'shipment_price_for_client' => 22,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                ],
                'hide' => [
                    'id' => 1,
                    'created_at' => 6,
                    'section' => 8,
                    'customer.addresses.email' => 13,
                    'customer.address.firstname' => 14,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'profit' => 17,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ]
            ],
            'consultant' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'actions' => 7,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'shipment_price_for_client' => 22,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                ],
                'hide' => [
                    'id' => 1,
                    'created_at' => 6,
                    'section' => 8,
                    'customer.addresses.email' => 13,
                    'customer.address.firstname' => 14,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'profit' => 17,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ]
            ],
            'storekeeper' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'actions' => 7,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'shipment_price_for_client' => 22,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                ],
                'hide' => [
                    'id' => 1,
                    'created_at' => 6,
                    'section' => 8,
                    'customer.addresses.email' => 13,
                    'customer.address.firstname' => 14,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'profit' => 17,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ]
            ]
        ],
        'third_group' => [
            'super_admin' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.address.firstname' => 14,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                    
                ],
                'hide' => [
                    'customer.addresses.email' => 13,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    
                ]
            ],
            'admin' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.address.firstname' => 14,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                    
                ],
                'hide' => [
                    'customer.addresses.email' => 13,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                ]
            ],
            'accountant' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.address.firstname' => 14,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                    
                ],
                'hide' => [
                    'customer.addresses.email' => 13,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                ]
            ],
            'consultant' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.address.firstname' => 14,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                    
                ],
                'hide' => [
                    'customer.addresses.email' => 13,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                ]
            ],
            'storekeeper' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.address.firstname' => 14,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                    
                ],
                'hide' => [
                    'customer.addresses.email' => 13,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                ]
            ]
        ],
        'show_all' => [
            'super_admin' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.addresses.email' => 13,
                    'customer.address.firstname' => 14,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ],
                'hide' => [
                ]
            ],
            'admin' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.addresses.email' => 13,
                    'customer.address.firstname' => 14,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ],
                'hide' => [
                ]
            ],
            'accountant' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.addresses.email' => 13,
                    'customer.address.firstname' => 14,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ],
                'hide' => [

                ]
            ],
            'consultant' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.addresses.email' => 13,
                    'customer.address.firstname' => 14,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ],
                'hide' => [

                ]
            ],
            'storekeeper' => [
                'show' => [
                    'sent' => 2,
                    'not_sent' => 3,
                    'print' => 4,
                    'employee_id' => 5,
                    'created_at' => 6,
                    'actions' => 7,
                    'section' => 8,
                    'last_status_update_date' => 9,
                    'warehouse.symbol' => 10,
                    'customer_notices' => 11,
                    'customer.addresses.phone' => 12,
                    'customer.addresses.email' => 13,
                    'customer.address.firstname' => 14,
                    'customer.address.lastname' => 15,
                    'customer.nick_allegro' => 16,
                    'profit' => 17,
                    'weight' => 18,
                    'products_value_gross' => 19,
                    'additional_service_cost' => 20,
                    'packing_warehouse_cost' => 21,
                    'shipment_price_for_client' => 22,
                    'shipment_price_for_us' => 23,
                    'sum_of_gross_values' => 24,
                    'sum_of_payments' => 25,
                    'left_to_pay' => 26,
                    'packages[0].shipment_date' => 27,
                    'labels' => 28,
                    'invoice_gross_sum' => 29,
                    'icons' => 30,
                    'consultant_earning' => 31,
                    'packages' => 32,
                    'shipment_price_for_client' => 33,
                    'correction_amount' => 34,
                    'correction_description' => 35,
                    'document_number' => 36,
                ],
                'hide' => [

                ]
            ]
        ],
    ],
];