<?php

return [
    'host'       => env('MAIL_NOTIFICATION_HOST', 's84.cyber-folks.pl'),
    'username'   => env('MAIL_NOTIFICATION_USERNAME', 'awizacje@ephpolska.pl'),
    'password'   => env('MAIL_NOTIFICATION_PASSWORD', '1!Qaa2@Wss'),
    'port'       => env('MAIL_NOTIFICATION_PORT', 587),
    'encryption' => env('MAIL_NOTIFICATION_ENCRYPTION', 'tls'),
    'from'       => env('MAIL_NOTIFICATION_FROM', 'awizacje@ephpolska.pl'),
];
APP_NAME=Laravel
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret

REDIS_PASSWORD=null
REDIS_PORT=6379
#
MAIL_DRIVER=smtp
MAIL_HOST=s84.cyber-folks.pl
MAIL_PORT=465
MAIL_USERNAME=info@ephpolska.pl.pl
MAIL_PASSWORD=C#2e1)Ic4}%W31@
MAIL_ENCRYPTION=SSL
MAIL_FROM_ADDRESS=info@ephpolska.pl
MAIL_FROM_NAME="EPH polska"

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

ACCOUNT_NUMBER=58160011561846167560000001
APP_NAME="EPH Polska"
APP_ENV=production
APP_KEY=base64:02IIyFaBodEsWYY0DuGX2BRT2qvduv1+r9Z1GBvu2yA=
APP_DEBUG=true
APP_URL=https://www.admin.mega1000.pl/
DOMAIN_NAME=mega1000.pl

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=admin1000
DB_USERNAME=system
DB_PASSWORD=test111

DB_CONNECTION_OLDFRONT=mysql
DB_HOST_OLDFRONT=mysql-old
DB_PORT_OLDFRONT=3306
DB_DATABASE_OLDFRONT=homestead
DB_USERNAME_OLDFRONT=homestead
DB_PASSWORD_OLDFRONT=secret


BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=database
QUEUE_DRIVER=database
SESSION_DRIVER=file
SESSION_LIFETIME=240

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
#
MAIL_DRIVER=smtp
MAIL_HOST=s84.cyber-folks.pl
MAIL_PORT=465
MAIL_USERNAME=info@ephpolska.pl.pl
MAIL_PASSWORD=C#2e1)Ic4}%W31@
MAIL_ENCRYPTION=SSL
MAIL_FROM_ADDRESS=info@ephpolska.pl

GIT_BOT_KEY=bb95277a964c66e7322a2ac15ae868c7e54b5943

GIT_BOT_KEY=bb95277a964c66e7322a2ac15ae868c7e54b5943
GIT_BOT_LOGIN=ventus-bot

INPOST_AUTHORIZATION_KEY=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzQlpXVzFNZzVlQnpDYU1XU3JvTlBjRWFveFpXcW9Ua2FuZVB3X291LWxvIn0.eyJleHAiOjIwMTk1NzQxODEsImlhdCI6MTcwNDIxNDE4MSwianRpIjoiZWYwYThkYzEtYTZlZi00ZTNmLTk0ZjUtNDZkNDllNzljZWQwIiwiaXNzIjoiaHR0cHM6Ly9sb2dpb
i5pbnBvc3QucGwvYXV0aC9yZWFsbXMvZXh0ZXJuYWwiLCJzdWIiOiJmOjEyNDc1MDUxLTFjMDMtNGU1OS1iYTBjLTJiNDU2OTVlZjUzNTppNmR3SUFfdzI3VDN1WlN2RzJWWnhCaWRMQV9rYW5pYUJPNmdOVWNsWEwwIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoic2hpcHgiLCJzZXNzaW9uX3N0YXRlIjoiNjMwNjRlMjQtOTVjOC00ZDNlLWIwM2EtN2IwNGFkYmN
kZDdjIiwic2NvcGUiOiJvcGVuaWQgYXBpOmFwaXBvaW50cyBhcGk6c2hpcHgiLCJzaWQiOiI2MzA2NGUyNC05NWM4LTRkM2UtYjAzYS03YjA0YWRiY2RkN2MiLCJhbGxvd2VkX3JlZmVycmVycyI6IiIsInV1aWQiOiI0NzVkYmNjOS1hZjdhLTQxZDQtYWY0My1lNGRlMGI3OGIyOWEiLCJlbWFpbCI6ImtzaWVnb3dvc2NAZXBocG9sc2thLnBsIn0.i0bdgPK8A
UbUxLu9ojCekMz9mvM8AFclJ1OIhEdPeSOTGIVhQ2G5vW9OrfAFL2z9o97qsNji9ZN_v-YPuEE7twXqHh8sfibtahRm3C4WalbBoHUYmCxqYSGRU_Tu65zZ1YnUzNvRZD7rSoKXL2WW1gezG74JJpqDzMtcH7-cRX1rpOepJrGcwp6pGYUICnh_Lkf2cT3mba6-7qlEn0wFVikjfx4U9kfphokR2BDuiicOPXpWcsfNQl0p9mgJh3cgKATRKohZYw9YdR78CjRSri1
uVhXly_1vkMZEb7keAI41zjSwENDzn28nngOjLV6Usi7r72DijQ_3ZmU0Gazhwg
INPOST_ORG_ID=83735
INPOST_URL=https://api-shipx-pl.easypack24.net
APACZKA_PASSWORD=1!Qqaaaa
APACZKA_API_KEY=apaczka123apaczka123
APACZKA_APP_ID=1311068_5e58d28b4c7ab7.36738713
APACZKA_APP_SECRET=8mx3x6j9sb67nna356vk8ewes37h4r3b

IMAP_PASSWORD=jgB2bcx80RczEKQI8D
IMAP_INBOX={84.cyber-folks.pl:993/imap/ssl}INBOX

VAT=0.23
PACKAGE_DIVIDE_MARGIN=1.3
MIX_LABEL_WAITING_FOR_PAYMENT_ID=64
MIX_LABEL_ENTER_PAYMENT_DATE_ID=63

VAT=0.23

APACZKA_PASSWORD=
APACZKA_API_KEY=
APACZKA_APP_ID=
APACZKA_APP_SECRET=
INPOST_AUTHORIZATION_KEY=
INPOST_ORG_ID=
INPOST_URL=
SENTRY_LARAVEL_DSN=https://c0bcc769b6c24e609f6a04bafd85e0e8@sentry.io/1405022
ALLEGRO_SANDBOX=false
ALLEGRO_CLIENT_ID=
ALLEGRO_CLIENT_SECRET=
GLS_LOGIN=
GLS_PASSWORD=
GLS_API_URL=

POCZTEX_LOGIN=
POCZTEX_PASSWORD=
POCZTEX_TRACE=
POCZTEX_URL=http://mobilna.poczta-polska.pl/MobiPost/getpackage?action=getPackageData&search=

SCHENKER_DATES_FORMAT="Y-m-d\\TH:i:s"
SCHENKER_USER_NAME=""
SCHENKER_USER_PASSWORD=""
SCHENKER_CLIENT_ID=""

SENDER_NAME="Elektroniczna Platforma Handlowa Sp z o. o."
SENDER_TAX_NUMBER="8982272269"
SENDER_POST_CODE="50-305"
SENDER_CITY="Wrocław"
SENDER_STREET="Stefana Jaracza"
SENDER_HOUSE_NUMBER="22"
SENDER_LOCAL_NUMBER="12"
SENDER_EMAIL="spedycja@ephpolska.pl"
SENDER_PHONE="691801594"
SENDER_CONTACT_PERSON="Wojciech Weissbrot"

PAYER_NAME="Elektroniczna Platforma Handlowa Sp z o. o."
PAYER_TAX_NUMBER="8982272269"
PAYER_POST_CODE="50-305"
PAYER_CITY="Wrocław"
PAYER_STREET="Stefana Jaracza"
PAYER_HOUSE_NUMBER="22"
PAYER_LOCAL_NUMBER="12"
PAYER_EMAIL="spedycja@ephpolska.pl"
PAYER_PHONE="691801594"
PAYER_CONTACT_PERSON="Wojciech Weissbrot"

MAIL_NOTIFICATION_HOST=s84.cyber-folks.pl
MAIL_NOTIFICATION_USERNAME=awizacje@ephpolska.pl
MAIL_NOTIFICATION_PASSWORD=1!Qaa2@Wss
MAIL_NOTIFICATION_PORT=587
MAIL_NOTIFICATION_ENCRYPTION=tls
MAIL_NOTIFICATION_FROM=awizacje@ephpolska.pl

XML_FOR_NEXO_PATH="/XMLFS/"




