<?php

namespace App\Helpers;

class LabelsHelper
{
    const FINISH_LOGISTIC_LABEL_ID = 68;
    const TRANSPORT_SPEDITION_INIT_LABEL_ID = 103;
    const WAIT_FOR_SPEDITION_FOR_ACCEPT_LABEL_ID = 107;
    const VALIDATE_ORDER = 45;
    const SEND_TO_WAREHOUSE_FOR_VALIDATION = 52;
    const WAIT_FOR_WAREHOUSE_TO_ACCEPT = 47;
    const INVALID_ORDER_ADDRESS = 184;
}
